services:
  - type: web
    name: MataTuutor
    env: static
    buildCommand: npm start
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html